# Generated by Django 5.2.8 on 2025-11-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resena', '0002_remove_resena_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='resena',
            name='autor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
