# Generated by Django 5.2.8 on 2025-11-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resena', '0004_populate_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resena',
            name='autor',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
