# Generated by Django 5.2.8 on 2025-11-12 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resena', '0005_alter_resena_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoResena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='resenas/')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('resena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='resena.resena')),
            ],
            options={
                'verbose_name': 'Foto Reseña',
                'verbose_name_plural': 'Fotos de Reseñas',
                'db_table': 'fotos_resena',
            },
        ),
    ]
