# Generated by Django 5.2.8 on 2025-11-12 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resena', '0006_fotoresena'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resena',
            name='servicio',
        ),
        migrations.RemoveField(
            model_name='resena',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='FotoResena',
        ),
        migrations.DeleteModel(
            name='Resena',
        ),
    ]
