# Generated by Django 5.2.8 on 2025-11-12 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resena', '0007_remove_resena_servicio_remove_resena_usuario_and_more'),
        ('servicios', '0003_fotolugar'),
        ('usuarios', '0004_alter_administrador_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=200)),
                ('destino', models.CharField(max_length=300)),
                ('mensaje', models.TextField()),
                ('calificacion', models.IntegerField(default=5)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='servicios.servicio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'db_table': 'resenas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='FotoResena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='resenas/')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('resena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='resena.resena')),
            ],
            options={
                'verbose_name': 'Foto Reseña',
                'verbose_name_plural': 'Fotos de Reseñas',
                'db_table': 'fotos_resena',
            },
        ),
    ]
