# Generated by Django 5.2.8 on 2025-11-06 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_admin_make_ptr_nullable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrador',
            options={'verbose_name': 'Administrador', 'verbose_name_plural': 'Administradores'},
        ),
        migrations.AlterModelOptions(
            name='propietario',
            options={'verbose_name': 'Propietario', 'verbose_name_plural': 'Propietarios'},
        ),
        migrations.AlterModelOptions(
            name='turista',
            options={'verbose_name': 'Turista', 'verbose_name_plural': 'Turistas'},
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='id',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='puede_eliminar_contenido',
        ),
        migrations.RemoveField(
            model_name='propietario',
            name='id',
        ),
        migrations.RemoveField(
            model_name='turista',
            name='id',
        ),
        migrations.AlterField(
            model_name='administrador',
            name='usuario_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='usuario_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='turista',
            name='preferencias',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='turista',
            name='usuario_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.usuario'),
        ),
        migrations.AlterModelTable(
            name='administrador',
            table='administradores',
        ),
        migrations.AlterModelTable(
            name='propietario',
            table='propietarios',
        ),
        migrations.AlterModelTable(
            name='turista',
            table='turistas',
        ),
    ]
