# Generated by Django 5.2.8 on 2025-11-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaCultural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(max_length=100)),
                ('contenido', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Guía Cultural',
                'verbose_name_plural': 'Guías Culturales',
                'db_table': 'guias_culturales',
            },
        ),
    ]
