# Generated by Django 5.2.8 on 2025-11-06 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0004_alter_administrador_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('tipo_servicio', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_propios', to='usuarios.propietario')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'servicios',
            },
        ),
        migrations.CreateModel(
            name='Atraccion',
            fields=[
                ('servicio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='servicios.servicio')),
                ('nombre_lugar', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Atracción',
                'verbose_name_plural': 'Atracciones',
                'db_table': 'atracciones',
            },
            bases=('servicios.servicio',),
        ),
        migrations.CreateModel(
            name='LugaresTuristico',
            fields=[
                ('servicio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='servicios.servicio')),
                ('nombre_lugar', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Lugar Turístico',
                'verbose_name_plural': 'Lugares Turísticos',
                'db_table': 'lugares_turisticos',
            },
            bases=('servicios.servicio',),
        ),
        migrations.CreateModel(
            name='MedioTransporte',
            fields=[
                ('servicio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='servicios.servicio')),
                ('nombreEmpresa', models.CharField(max_length=150)),
                ('tipo_transporte', models.CharField(max_length=100)),
                ('nombreCooperativa', models.CharField(blank=True, max_length=200, null=True)),
                ('ruta', models.TextField(blank=True, null=True)),
                ('tarifa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('distancia_km', models.IntegerField(blank=True, null=True)),
                ('tiempo_estimado_min', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Medio de Transporte',
                'verbose_name_plural': 'Medios de Transporte',
                'db_table': 'medios_transporte',
            },
            bases=('servicios.servicio',),
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visita', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ira', 'Irá'), ('no_ira', 'No irá'), ('cancelado', 'Cancelado')], default='ira', max_length=20)),
                ('nota', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='servicios.servicio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'db_table': 'visitas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('lugaresturistico_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='servicios.lugaresturistico')),
                ('clasificacion', models.CharField(max_length=255)),
                ('servicios_hotel', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hoteles',
                'db_table': 'hoteles',
            },
            bases=('servicios.lugaresturistico',),
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('lugaresturistico_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='servicios.lugaresturistico')),
                ('tipoComida', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Restaurante',
                'verbose_name_plural': 'Restaurantes',
                'db_table': 'restaurantes',
            },
            bases=('servicios.lugaresturistico',),
        ),
        migrations.AddField(
            model_name='servicio',
            name='medioTransporte',
            field=models.ForeignKey(blank=True, db_column='id_transporte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to='servicios.mediotransporte'),
        ),
    ]
