# Generated by Django 5.2.8 on 2025-11-12 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_visita_lugar_alter_visita_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoLugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='lugares/')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='servicios.lugaresturistico')),
            ],
            options={
                'verbose_name': 'Foto Lugar',
                'verbose_name_plural': 'Fotos de Lugares',
                'db_table': 'fotos_lugar',
            },
        ),
    ]
